# Generated by Django 2.0.7 on 2018-10-16 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamesetmatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('match_type', models.CharField(choices=[('RR', 'Round Robin'), ('SR', 'Seeding'), ('KR', 'Knockout')], default='SR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, default='', max_length=1)),
                ('seeding_points', models.CharField(blank=True, default='', max_length=3)),
                ('rr_points', models.CharField(blank=True, default='', max_length=2)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_set1', models.CharField(blank=True, default='', max_length=2)),
                ('team2_set1', models.CharField(blank=True, default='', max_length=2)),
                ('team1_set2', models.CharField(blank=True, default='', max_length=2)),
                ('team2_set2', models.CharField(blank=True, default='', max_length=2)),
                ('team1_set3', models.CharField(blank=True, default='', max_length=2)),
                ('team2_set3', models.CharField(blank=True, default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile_2', to=settings.AUTH_USER_MODEL)),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_year', models.DateField()),
                ('tour_type', models.CharField(choices=[('ST', 'Singles Tournament'), ('DT', 'Doubles Tournament'), ('MT', 'Mixed Doubles Tournament')], default='ST', max_length=2)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='gamesetmatch.Match')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerseedinggame',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='playerseedinggame',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='player',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerSeedingGame',
        ),
        migrations.DeleteModel(
            name='PlayerStat',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='gamesetmatch.Score'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='gamesetmatch.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='gamesetmatch.Team'),
        ),
    ]
