# Generated by Django 2.0.7 on 2018-10-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0002_auto_20181016_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='division',
            field=models.CharField(choices=[('DIV_1', 'Division 1'), ('DIV_2', 'Division 2'), ('DIV_3', 'Division 3')], default='DIV_3', max_length=2),
        ),
    ]
