# Generated by Django 2.0.7 on 2018-10-16 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0005_auto_20181016_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_3',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
