# Generated by Django 2.0.7 on 2018-10-16 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0007_auto_20181016_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
