# Generated by Django 2.0.7 on 2018-10-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0008_auto_20181016_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match_score', to='gamesetmatch.Match'),
        ),
    ]
