# Generated by Django 2.0.7 on 2018-10-18 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0010_auto_20181018_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
