# Generated by Django 2.0.7 on 2018-10-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetmatch', '0012_auto_20181018_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_1',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_2',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_3',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
